name: Sync Notion to GitHub

on:
  schedule:
    - cron: '0 3 * * *'     # 매일 아침 3시에 자동 실행
  workflow_dispatch:         # 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Notion sync script
        run: python notion_to_github.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      - name: Commit and push changes
        run: |
          git config user.name "notion-bot"
          git config user.email "bot@example.com"
          git add .
          git commit -m "Auto update from Notion" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAGE_TOKEN }}@github.com/SeungahhHam/seungahhham.github.io.git
          git push origin main
